name: Cron Test

on:
  push:
  schedule:
    - cron: "*/15 * * * 0,2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run test
        run: echo "Workflow works"
